site_name: MARCIA Documentation
site_url: https://hameye.github.io/MARCIA/
site_description: TestDesc
repo_url: https://github.com/hameye/marcia
edit_uri: ''  #disables edit button


repo_name: hameye/marcia
use_directory_urls: false

theme:
  name: material
  palette: 
    scheme: mca
  icon:
    repo: fontawesome/brands/github
    language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
  logo: assets/images/icon.png
  favicon: assets/images/icon.png


nav:
  - Home: index.md
  - Installation: 
    - Python Installation: python_install.md
    - MARCIa Installation: marcia_install.md
  - User Guides: 
    - Sample Classification: examples/Tutorial_fr.ipynb
    - Features Extraction: examples/Features_extraction_fr.ipynb
  - Code Documentation:
    - Objects: 
      - Datacube: code_reference/datacube.md
      - Mask: code_reference/mask.md
    - Fitting:
      - Manual Fitting: code_reference/manual_fit.md
    - IO:
      - Datacube: code_reference/data_io.md
      - Mask: code_reference/mask_io.md
    - Plotting: 
      - Datacube: code_reference/plotting.md
      


markdown_extensions:
- admonition
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.inlinehilite
- pymdownx.snippets:
    check_paths: true

# - pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
  - search
  - autolinks
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: false
            show_source: true
            show_category_heading: true
          selection:
            filters:
              - "!^_"  # exlude all members starting with _
      watch:
        - src/marcia

extra_css:
  - stylesheets/extra.css
  - css/style.css

copyright: Copyright &copy; 2020 - 2021 Hadrien Meyer