site_name: MARCIA Documentation
site_url: https://hameye.github.io/MARCIA/
site_description: TestDesc
repo_url: https://github.com/hameye/marcia
edit_uri: ''  #disables edit button


repo_name: hameye/marcia
use_directory_urls: false

theme:
  name: material
  palette: 
    scheme: mca
  icon:
    repo: fontawesome/brands/github
    language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
  logo: assets/images/icon.png
  favicon: assets/images/icon.png


nav:
  - Home: index.md
  - Installation: 
    - Python Installation: python_install.md
    - MARCIA Installation: marcia_install.md
  - User Guides: 
    - Quick Start: examples/quick-start.ipynb
    - Sample Classification: examples/Tutorial_fr.ipynb
  - Code Documentation:
    - Objects: 
      - Datacube: code_reference/datacube.md
      - Mask: code_reference/mask.md
    - Fitting:
      - Manual Fitting: code_reference/manual_fit.md
    - IO:
      - Datacube: code_reference/data_io.md
      - Mask: code_reference/mask_io.md
    - Plotting: 
      - Datacube: code_reference/plotting.md
      


markdown_extensions:
- admonition
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.inlinehilite
- pymdownx.snippets:
    check_paths: true

# - pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
  - search
  - autorefs
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
      execute: True
  - mkdocstrings:
      handlers: 
        python:
          options:
            filters: ["!^_"]  # exlude all members starting with _
            members_order: "source"
            merge_init_into_class: False
            show_signature: False
            show_source: False
            show_root_toc_entry: False
            # show_signature_annotations: True
          import:
          - https://docs.python.org/3/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          - https://pandas.pydata.org/pandas-docs/stable/objects.inv
extra_css:
  - stylesheets/extra.css
  - css/style.css

copyright: Copyright &copy; 2020 - 2023 Hadrien Meyer